on:
  push:
    branches:
      - "main"
  pull_request:

name: "Build hooks-cli"

jobs:
  build:
    name: "Build source code"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.38.2

      - name: "Install dependencies"
        run: | 
          cd packages/hooks-cli
          deno cache --unstable cli.ts
      
      - name: "Compile"
        run: | 
          cd packages/hooks-cli
          mkdir artifacts
          deno compile --target aarch64-apple-darwin --output artifacts/hooks-cli-aarch64-apple-darwin cli.ts
          deno compile --target x86_64-apple-darwin --output artifacts/hooks-cli-x86_64-apple-darwin cli.ts
          deno compile --target x86_64-pc-windows-msvc --output artifacts/hooks-cli-x86_64-pc-windows-msvc cli.ts 
          deno compile --target x86_64-unknown-linux-gnu --output artifacts/hooks-cli-x86_64-unknown-linux-gnu cli.ts
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hooks-cli executables
          path: |
            packages/hooks-cli/artifacts/hooks-cli-aarch64-apple-darwin
            packages/hooks-cli/artifacts/hooks-cli-x86_64-apple-darwin
            packages/hooks-cli/artifacts/hooks-cli-x86_64-pc-windows-msvc.exe
            packages/hooks-cli/artifacts/hooks-cli-x86_64-unknown-linux-gnu
