on:
  push:
    branches:
      - "main"
  pull_request:

name: "Build hooks-rs"

jobs:
  build:
    name: "Build Rust source code"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: hooks-rs
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"

      - name: "Use Rust nightly"
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "nightly"
          target: "wasm32-unknown-unknown"
          components: "clippy,rustfmt"
          override: true

      - name: "Install gcc-multilib"
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib

      - name: "Build Rust project"
        run: |
          cargo build --target wasm32-unknown-unknown
