on:
  push:
    branches:
      - "main"
  pull_request:

name: "Lint"

jobs:
  lint:
    name: "Lints"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: hooks-rs
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"

      - name: "Use Rust nightly"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: nightly
          profile: "minimal"
          components: "clippy,rustfmt"
          override: true

      - name: "Use Rust cache"
        uses: "Swatinem/rust-cache@v2"
        with:
          cache-on-failure: true

      - name: "Add wasm32-unknown-unknown target"
        run: |
          rustup target add wasm32-unknown-unknown

      - name: "Install prettier"
        run: |
          yarn global add prettier@3.0.3

      - name: "Install gcc-multilib"
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib

      - name: "Check prettier format"
        run: |
          prettier --ignore-path .gitignore --check .

      - name: "Check Rust format"
        run: |
          cargo +nightly fmt --all -- --check

      - name: "Run Clippy lints"
        run: |
          cargo +nightly clippy --all -- -D warnings
