on:
  push:
    branches:
      - "main"
  pull_request:

name: "Lint hooks-cli"

jobs:
  lint:
    name: "Lints"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.38.2

      - name: "Run Deno format in packages/hooks-cli"
        run: |
          cd packages/hooks-cli
          deno fmt --unstable

      - name: "Run Deno lints in packages/hooks-cli"
        run: |
          cd packages/hooks-cli
          deno lint --unstable
