on:
  push:
    branches:
      - "main"
  pull_request:

name: "Lint hooks-rs"

jobs:
  lint:
    name: "Lints"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"

      - name: "Use Rust nightly"
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "nightly"
          target: "wasm32-unknown-unknown"
          components: "clippy,rustfmt"
          override: true

      - name: "Install gcc-multilib"
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib

      - uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x

      - name: "Check prettier format in hooks-rs"
        run: |
          cd hooks-rs
          npx prettier@3.4.2 --check .

      - name: "Check Rust format in hooks-rs"
        run: |
          cd hooks-rs
          cargo +nightly fmt --all -- --check

      - name: "Run Clippy lints in hooks-rs"
        run: |
          cd hooks-rs
          cargo +nightly clippy --all -- -D warnings
