on:
  push:
    branches:
      - "main"
  pull_request:

name: "Lint hooks-rs"

jobs:
  lint:
    name: "Lints"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"

      - name: "Use Rust nightly"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: nightly
          profile: "minimal"
          components: "clippy,rustfmt"
          override: true

      - name: "Use Rust cache"
        uses: "Swatinem/rust-cache@v2"
        with:
          cache-on-failure: true

      - name: "Add wasm32-unknown-unknown target"
        run: |
          rustup target add wasm32-unknown-unknown

      - name: "Install prettier"
        run: |
          yarn global add prettier@3.0.3

      - name: "Install gcc-multilib"
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.38.2

      - name: "Check prettier format in hooks-rs"
        run: |
          cd hooks-rs
          prettier --ignore-path .gitignore --check .

      - name: "Check Rust format in hooks-rs"
        run: |
          cd hooks-rs
          cargo +nightly fmt --all -- --check

      - name: "Run Clippy lints in hooks-rs"
        run: |
          cd hooks-rs
          cargo +nightly clippy --all -- -D warnings
