on:
  push:
    branches:
      - "main"
  pull_request:

name: "Test hooks-rs"

jobs:
  test:
    timeout-minutes: 30
    name: "Run tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"

      - name: "Use Rust nightly"
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "nightly-2024-10-17"
          target: "wasm32-unknown-unknown"
          components: "clippy,rustfmt"
          override: true

      - name: "Install wasm-pack"
        uses: actions-rs/cargo@v1
        with:
          command: "install"
          args: "wasm-pack --locked --version 0.11.1"

      - name: "Install hook cleaner"
        run: |
          git clone https://github.com/XRPLF/hook-cleaner-c
          cd hook-cleaner-c
          git reset --hard b856a3614c00361f108d07379f5892e7347bb994
          make
          chmod u+x hook-cleaner
          echo $PWD >> $GITHUB_PATH

      - name: "Install hook guard checker"
        run: |
          git clone https://github.com/RichardAH/guard-checker/
          cd guard-checker
          git reset --hard de69e8aa054d49612dda7046962003beb88c0749
          make
          chmod u+x guard_checker
          echo $PWD >> $GITHUB_PATH

      - name: "Install wasm-opt"
        run: |
          cargo install wasm-opt --locked
          wasm-opt -h

      - name: "Install gcc-multilib"
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib

      - name: "Install wasm2wat"
        run: |
          curl -L https://github.com/WebAssembly/wabt/releases/download/1.0.33/wabt-1.0.33-ubuntu.tar.gz -O    
          tar -xzf wabt-1.0.33-ubuntu.tar.gz  
          cd ./wabt-1.0.33/bin
          chmod u+x ./wasm2wat
          echo $PWD >> $GITHUB_PATH

      - name: "Check wasm2wat installation"
        run: |
          wasm2wat --help

      - name: "Setup Node.js test environment"
        uses: actions/setup-node@v3
        with:
          node-version-file: "./hooks-rs/tests/.nvmrc"
          cache: "npm"
          cache-dependency-path: "hooks-rs/tests/package-lock.json"

      - name: "Run lib tests"
        run: |
          cd hooks-rs
          wasm-pack test --node

      - name: "Build examples"
        run: |
          cd hooks-rs
          cargo build --examples

      - name: "Run integration tests"
        run: |
          cd hooks-rs/tests
          npm ci
          npm test
