on:
  push:
    branches:
      - "main"
  pull_request:

name: "test"

jobs:
  test:
    name: "Run tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"

      - name: "Use Rust nightly"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: nightly
          profile: "minimal"
          components: "clippy,rustfmt"
          override: true

      - name: "Use Rust cache"
        uses: "Swatinem/rust-cache@v2"
        with:
          cache-on-failure: true

      - name: "Add wasm32-unknown-unknown target"
        run: |
          rustup target add wasm32-unknown-unknown

      - name: "Install wasm-pack"
        uses: actions-rs/cargo@v1
        with:
          command: "install"
          args: "wasm-pack --locked --version 0.12.1"

      - name: "Run lib tests"
        run: |
          wasm-pack test --node

      - name: "Build examples"
        run: |
          cargo build --examples

      # TODO: do what https://github.com/Transia-RnD/hooks-toolkit-ts/blob/main/.github/workflows/nodejs.yml does
      # - name: "Run examples"
      #   run: |
