on:
  push:
    branches:
      - "main"
  pull_request:

name: "Test"

jobs:
  test:
    timeout-minutes: 30
    name: "Run tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"

      - name: "Use Rust nightly"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: nightly
          profile: "minimal"
          components: "clippy,rustfmt"
          override: true

      - name: "Use Rust cache"
        uses: "Swatinem/rust-cache@v2"
        with:
          cache-on-failure: true

      - name: "Add wasm32-unknown-unknown target"
        run: |
          rustup target add wasm32-unknown-unknown

      - name: "Install wasm-pack"
        uses: actions-rs/cargo@v1
        with:
          command: "install"
          args: "wasm-pack --locked --version 0.12.1"

      - name: "Install hook cleaner"
        run: |
          git clone https://github.com/XRPLF/hook-cleaner-c
          cd hook-cleaner-c
          git reset --hard b856a3614c00361f108d07379f5892e7347bb994
          make
          chmod u+x hook-cleaner
          echo $PWD >> $GITHUB_PATH

      - name: "Install hook guard checker"
        run: |
          git clone https://github.com/RichardAH/guard-checker/
          cd guard-checker
          git reset --hard de69e8aa054d49612dda7046962003beb88c0749
          make
          chmod u+x guard_checker
          echo $PWD >> $GITHUB_PATH

      - name: "Install wasm-opt"
        run: |
          cargo install wasm-opt --locked
          wasm-opt -h

      - name: "Setup Node.js test environment"
        uses: actions/setup-node@v3
        with:
          node-version-file: "./tests/.nvmrc"
          cache: "npm"
          cache-dependency-path: "tests/package-lock.json"

      - name: "Run lib tests"
        run: |
          wasm-pack test --node

      - name: "Build examples"
        run: |
          cargo build --examples

      - name: "Run integration tests"
        run: |
          cd tests
          npm ci
          npm test
